config/routes.rb
Rails.application.routes.draw do
  resources :students, only: [:index]

  #this is temporarily the default URL
  root to: 'students#index'
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :first_name, :last_name, presence: true

  def full_name
    [title, first_name, middle_name, last_name].compact.join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  PER_PAGE = 10
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.paginate(page: params[:page], per_page: PER_PAGE)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/will_paginate_helper.rb
module WillPaginateHelper
  class CustomRenderer < WillPaginate::ActionView::LinkRenderer
    def to_html
      html = '<ul class="pagination">'
      html += pagination.map do |item|
        item.is_a?(Integer) ?
          page_number(item) :
          send(item)
      end.join()
      html += '</ul>'
    end
    def page_number(page)
      if page == current_page
        tag(:li, "<a href='/students?page=#{page}'>#{page}</a>", class: "active")
      else
        tag(:li, "<a href='/students?page=#{page}'>#{page}</a>")
      end
    end
    def previous_or_next_page(page, text, classname, aria_label = nil)
      if page
        tag(:li, "<a href='/students?page=#{page}'>#{text}</a>")
      else
        tag(:li, "<a>#{text}</a>", class: "disabled")
      end
    end
    def gap
      tag(:li, "<a href=''>...</a>", class: "disabled")
    end
  end
  def will_paginate_nicely(collection)
    will_paginate(
      collection, 
      inner_window: 1,
      outer_window: 0,
      next_label: '>',
      previous_label: '<',
      renderer: CustomRenderer
    )
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MySMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/students/_student.html.erb
<tr>
  <td>
    <%= student.full_name %>
  </td>
  <td>
    <%= student.email %>
  </td>
  <td>
    <%= student.birth_date %>
  </td>
  <td>
    <%= student.gender %>
  </td>
</tr>    

app/views/students/edit.html.erb
<h1>Students</h1>
<%= link_to "Cancel", @student, role:"button", class: "btn btn-default" %>
<p>Sure would be nice if you could edit something from here</p>

app/views/students/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'stylesheets/students' %>
<% end %>

<h1>Students</h1>
<%= will_paginate_nicely @students %>
<table class="table">
  <thead>
    <tr>
      <th width="40%">
        Name
      </th>
      <th width="40%">
        Email
      </th>
      <th width="10%">
        Birth Date
      </th>
      <th width="10%">
        Gender
      </th>
    </tr>
  </thead>
  <tbody>
    <% if @students.empty? %>
      <tr><td colspan="4" class="center-text">There are no students currently in your system.</td></tr>
    <% else %>
      <%= render partial: 'student', collection: @students %>
    <% end %>
  </tbody>
</table>
<%= will_paginate_nicely @students %>

app/views/students/show.html.erb
<h1>Students</h1>
<%= link_to "Edit", edit_student_path(@student), role:"button", class: "btn btn-default" %>
<%= @student.full_name %>